global:
  scrape_interval: 5s
  external_labels:
    namespace: local

rule_files:
  - /etc/prometheus/recording-rules.yml
  - /etc/prometheus/alerting-rules.yml

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ 'localhost:9090' ]
        labels:
          container: 'prometheus'
          instance: 'redserver'

  - job_name: alertmanager
    static_configs:
      - targets: [ 'alertmanager:9093' ]
        labels:
          container: 'alertmanager'
          instance: 'redserver'

  - job_name: node-exporter
    static_configs:
      - targets: [ 'node-exporter:9100' ]
        labels:
          container: 'node-exporter'
          instance: 'redserver'
      - targets: [ '100.64.0.2:9100' ]
        labels:
          container: 'node-exporter'
          instance: 'crimsonserver'

  - job_name: cadvisor
    static_configs:
      - targets: [ 'cadvisor:8080' ]
        labels:
          container: 'cadvisor'
          instance: 'redserver'
  
  - job_name: docker-exporter
    static_configs:
      - targets: [ '100.64.0.2:9417' ]
        labels:
          container: 'docker-exporter'
          instance: 'crimsonserver'
