version: "3.8"

services:
  jellyfin:
    networks:
      - default
      - monitoring_net
      - proxy_net
    labels:
      logging_jobname: "jellyfin-logs"
      logging: "promtail"

networks:
  monitoring_net:
    external:
      name: monitoring
  proxy_net:
    external: true
