services:
  headscale:
    networks:
      - proxy_net
      - monitoring_net
    labels:
      logging_jobname: "headscale-stack"
      logging: "headscale"

  headplane:
    networks:
      - proxy_net
      - monitoring_net
    labels:
      logging_jobname: "headscale-stack"
      logging: "headscale"

networks:
  proxy_net:
    external: true
  monitoring_net:
    external: true
    name: monitoring
